#!/usr/bin/env python3
"""Tests for scripts/generate_filters.py and validate_rules.py."""

from __future__ import annotations

import subprocess
import sys
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = REPO_ROOT / "scripts"
FIXTURE = REPO_ROOT / "tests" / "fixtures" / "provider-rules.fixture.md"


def run_script(script: str, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPTS / script), *args],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


class TestValidateRules(unittest.TestCase):
    def test_fixture_passes(self) -> None:
        proc = run_script("validate_rules.py", str(FIXTURE))
        self.assertEqual(proc.returncode, 0, proc.stderr or proc.stdout)

    def test_template_passes(self) -> None:
        template = REPO_ROOT / "references" / "provider-rules.template.md"
        proc = run_script("validate_rules.py", str(template))
        self.assertIn(proc.returncode, (0, 2), proc.stderr or proc.stdout)


class TestGenerateFilters(unittest.TestCase):
    def setUp(self) -> None:
        self.out_dir = REPO_ROOT / "tests" / "tmp_output"
        self.out_dir.mkdir(parents=True, exist_ok=True)

    def tearDown(self) -> None:
        for name in ("gmail-filters.xml", "email-receive-rules.md"):
            path = self.out_dir / name
            if path.exists():
                path.unlink()

    def test_dry_run_rule_count(self) -> None:
        proc = run_script(
            "generate_filters.py",
            str(FIXTURE),
            "--dry-run",
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("Parsed 7 rules", proc.stdout)

    def test_generates_well_formed_xml(self) -> None:
        proc = run_script(
            "generate_filters.py",
            str(FIXTURE),
            "--output-dir",
            str(self.out_dir),
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)

        xml_path = self.out_dir / "gmail-filters.xml"
        md_path = self.out_dir / "email-receive-rules.md"
        self.assertTrue(xml_path.is_file())
        self.assertTrue(md_path.is_file())

        tree = ET.parse(xml_path)
        entries = tree.getroot().findall("{http://www.w3.org/2005/Atom}entry")
        self.assertEqual(len(entries), 7)

        md_text = md_path.read_text(encoding="utf-8")
        self.assertIn("Generated by `scripts/generate_filters.py`", md_text)

    def test_log_summary_flag(self) -> None:
        proc = run_script(
            "generate_filters.py",
            str(FIXTURE),
            "--output-dir",
            str(self.out_dir),
            "--log-summary",
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("Rules:", proc.stdout)
        self.assertIn(str(self.out_dir / "gmail-filters.xml"), proc.stdout)


class TestVersionSync(unittest.TestCase):
    def test_skill_version_matches_version_md(self) -> None:
        skill = (REPO_ROOT / "SKILL.md").read_text(encoding="utf-8")
        version_md = (REPO_ROOT / "VERSION.md").read_text(encoding="utf-8")

        skill_match = None
        for line in skill.splitlines()[:10]:
            if line.startswith("version:"):
                skill_match = line.split(":", 1)[1].strip()
                break

        md_match = None
        for line in version_md.splitlines():
            if line.startswith("**Current version:**"):
                md_match = line.split("**Current version:**", 1)[1].strip()
                break

        self.assertIsNotNone(skill_match, "SKILL.md frontmatter version missing")
        self.assertIsNotNone(md_match, "VERSION.md current version missing")
        self.assertEqual(skill_match, md_match)


if __name__ == "__main__":
    unittest.main()
