#!/usr/bin/env python3
"""Generate gmail-filters.xml and email-receive-rules.md from provider-rules.md."""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

SKIP_SECTION = re.compile(r"^##\s+Always skip", re.IGNORECASE)


def parse_table_rows(lines: list[str], start: int) -> tuple[list[dict[str, str]], int]:
    """Parse a markdown table starting at header line index."""
    if start >= len(lines) or not lines[start].strip().startswith("|"):
        return [], start

    header = [c.strip() for c in lines[start].strip().strip("|").split("|")]
    i = start + 2  # skip separator
    rows: list[dict[str, str]] = []

    while i < len(lines):
        line = lines[i].strip()
        if not line.startswith("|"):
            break
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < len(header):
            cells.extend([""] * (len(header) - len(cells)))
        row = dict(zip(header, cells))
        rows.append(row)
        i += 1

    return rows, i


def normalise_rule(row: dict[str, str]) -> dict[str, str] | None:
    """Return filter fields or None if row should be skipped."""
    domain = row.get("Domain", "").strip()
    label = row.get("Label", "").strip()
    default = row.get("Default", "keep").strip().lower()

    if not domain or not label:
        return None
    if domain.startswith("---") or label.startswith("---"):
        return None

    match = row.get("Match", "").strip()
    from_value = match if match else domain
    archive = default == "archive"

    return {
        "from": from_value,
        "label": label,
        "archive": archive,
        "domain": domain,
        "notes": row.get("Notes", "").strip(),
    }


def parse_provider_rules(path: Path) -> list[dict[str, str]]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    rules: list[dict[str, str]] = []
    i = 0

    while i < len(lines):
        if SKIP_SECTION.match(lines[i]):
            break
        if lines[i].strip().startswith("|") and "Domain" in lines[i]:
            table_rows, i = parse_table_rows(lines, i)
            for row in table_rows:
                rule = normalise_rule(row)
                if rule:
                    rules.append(rule)
            continue
        i += 1

    return rules


def build_xml(rules: list[dict[str, str]], title: str = "Mail Filters — Gmail Labeler") -> str:
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<feed xmlns="http://www.w3.org/2005/Atom" xmlns:apps="http://schemas.google.com/apps/2006">',
        f"  <title>{escape(title)}</title>",
        "  <id>tag:mail.google.com,2008:filters:gmail-labeler</id>",
        f"  <updated>{updated}</updated>",
        "  <author><name>gmail-labeler</name><email>generate_filters.py</email></author>",
    ]

    for rule in rules:
        parts.extend(
            [
                "  <entry>",
                '    <category term="filter"></category>',
                "    <title>Mail Filter</title>",
                "    <content></content>",
                f'    <apps:property name="from" value="{escape(rule["from"])}"/>',
                f'    <apps:property name="label" value="{escape(rule["label"])}"/>',
            ]
        )
        if rule["archive"]:
            parts.append('    <apps:property name="shouldArchive" value="true"/>')
        parts.append("  </entry>")

    parts.append("</feed>")
    return "\n".join(parts) + "\n"


def build_markdown(rules: list[dict[str, str]]) -> str:
    archive_rows = [r for r in rules if r["archive"]]
    keep_rows = [r for r in rules if not r["archive"]]

    def table(rows: list[dict[str, str]]) -> str:
        if not rows:
            return "_None_\n"
        lines = ["| From match | Label |", "|---|---|"]
        for r in rows:
            lines.append(f"| {r['from']} | {r['label']} |")
        return "\n".join(lines) + "\n"

    return f"""# Email receive rules — auto-categorisation

Generated by `scripts/generate_filters.py`. Import the companion
`gmail-filters.xml` in Gmail to apply these rules.

## How to apply

1. Gmail → **Settings (gear) → See all settings → Filters and Blocked Addresses**.
2. Scroll down → **Import filters** → choose `gmail-filters.xml` → **Open file**.
3. Review the list → tick **Apply new filters to existing conversations** to clear
   the backlog in one pass → **Create filters**.

When you add senders to `provider-rules.md`, re-run the generator and **re-import**
the updated XML.

## Rules — archive (marketing / newsletters / promos)

{table(archive_rows)}

## Rules — keep in inbox (records / billing / official mail)

{table(keep_rows)}

## Notes

- Filters match on **from** only. Multi-type brands need distinct `Match` patterns
  in `provider-rules.md` (see template `## Multi-type brands`).
- OTP, login codes, and personal mail have no filter rows (left untouched).
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Gmail filter files from provider-rules.md")
    parser.add_argument(
        "rules",
        nargs="?",
        default="references/provider-rules.md",
        help="Path to provider-rules.md (default: references/provider-rules.md)",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        default=".",
        help="Directory for gmail-filters.xml and email-receive-rules.md (default: .)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print rule count only")
    parser.add_argument("--title", default="Mail Filters — Gmail Labeler", help="XML feed title")
    args = parser.parse_args()

    rules_path = Path(args.rules)
    if not rules_path.is_file():
        print(f"Error: rules file not found: {rules_path}", file=sys.stderr)
        return 1

    rules = parse_provider_rules(rules_path)
    if not rules:
        print("Error: no filter rules parsed", file=sys.stderr)
        return 1

    archive_n = sum(1 for r in rules if r["archive"])
    keep_n = len(rules) - archive_n
    print(f"Parsed {len(rules)} rules ({archive_n} archive, {keep_n} keep) from {rules_path}")

    if args.dry_run:
        return 0

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    xml_path = out_dir / "gmail-filters.xml"
    md_path = out_dir / "email-receive-rules.md"

    xml_path.write_text(build_xml(rules, title=args.title), encoding="utf-8")
    md_path.write_text(build_markdown(rules), encoding="utf-8")

    print(f"Wrote {xml_path}")
    print(f"Wrote {md_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
